### ISSUE TITLE
sdk-hsm-thingy53/sample/02_rgb_led

### ISSUE THREAD

**Issue by Sriant** [HomeSmartMesh/sdk-hsm-thingy53#2]
Can you give me the detailed configuration of the device tree?

**Comment by wassfila** [comment]
I'm using a predefined device tree, did not create one in this repo. See the declaration here 
https://github.com/HomeSmartMesh/sdk-hsm-thingy53/blob/17828cb5aef531865aab6b7b1e8462148d3e42c7/samples/02_rgb_led/CMakeLists.txt#L10

the board  and the device tree you're looking for can be found in the Zephyr repo here
https://github.com/zephyrproject-rtos/zephyr/tree/main/boards/arm/thingy53_nrf5340

Closing as this is not an issue, rather a request for support. For future support requests, it is better to open a github discussion  
https://github.com/HomeSmartMesh/sdk-hsm-sensortag/discussions
